# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://www.sunziyang.com
date_format: "ordinal"
title: 随遇而安
subtitle: "在自由的空气中漂浮"
description: "孙梓洋的个人博客"
keywords: 孙梓洋, Ziyang Sun, ZvonimirSun, sunziyang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 3

# ---------------- #
#      Author      #
# ---------------- #
author: Ziyang Sun
github_username: ZvonimirSun
location: Sunzhou, China
email: i@sunziyang.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 5
lsi: false
quiet: false
excerpt_separator: "<!-- more -->"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions

repository: zvonimirsun/zvonimirsun.github.io


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: remarkbox, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zvonimirsun
    repo: zvonimirsun.github.io
    oauth:
        client_id: bdbc5c2d530ca59fd12a
        client_secret: 845c90824be260199ec0d72b67bafd00cb8c81ac
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zvonimirsun
    repo: zvonimirsun.github.io
    clientID: bdbc5c2d530ca59fd12a
    clientSecret: 845c90824be260199ec0d72b67bafd00cb8c81ac

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-105003596-1
