# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: https://Jessica1107.github.io
url: https://Jessica1107.github.io
date_format: "ordinal"
title: Jessica
subtitle: "Gone With Sakura ❀"
description: "Jessica's Blog"
keywords: Jessica,1107
favicon: /favicon.ico
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: Jessica
github_username: Jessica1107
location: Wuxi, China
email: lujiaying11@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions

repository: Jessica1107/Jessica1107.github.io

#github: f13721243e5a4baef76595f0fe3fb65f993272

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: remarkbox, gitment, gitalk, hypercomments, valine
comments_provider: valine

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
